## Configuration file for Jekyll
## & Schrift template

#
# Jekyll configuration
# --------------------

# Global
url: http://cleinias.xyz/

# Build options
markdown:    kramdown
permalink:   date

#Plugins

plugins:
        - jekyll-category-pages
        - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"


##################################
# Schrift template configuration #
##################################

# Enter below your name or pseudo & a short description
#    | These don't appear on the website. They are used to set the <META>s
author: Stefano Franchi
description: Cleinias. A philosopher's blog
title: A philosopher's blog # Appears in the window title of the browser. Stands alone on the homepage, sits beside the post title on post pages.

# Enter below the headtitle of your weblog/website
#    | It appears on the main navigation bar. You can use <span></span> to nicely fade out some part of it
#maintitle: Cleinias <span>Cleinias</span>
maintitle: <span>Cleinias</span>

# Enter below a short description that will sit next to your head title. (keep it short)
#    | {optional}
#maindesc: <a href=https://github.com/Schoewilliam/Schrift><span class=oi data-glyph=fork></span> Fork me</a>

# Enter below the items of your main menu
#    | Keep it a small amount. It is designed for a small menu.
#    | Schrift comes with the openiconic icon pack. Check out https://useiconic.com/open to select an icon for each menu item.
menus:
- text: Archive
  url: /archive
  openiconic: list
- text: Categories
  url: /categories.html
  openiconic: key
- text: Search
  url: /search
  openiconic: magnifying-glass
- text: About
  url: /about.html
  openiconic: info

# Enter an invitation message
#    | It lies right beneath every post to invite your readers to react and comment
#    | {optional}
#invitationmsg: If you have any feedback you would like me to read, please don't hesitate to send them over to <a href=mailto:you@domain.xyz>you@domain.xyz</a>.
